### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by pbsds** [TaserudConsulting/jsonresume-nix#2]
Some users may like a live-reload script while tweaking their resume. This is the one I cobbled together:

```nix
      apps = {
        live.type = "app";
        live.program = builtins.toString (
          pkgs.writeShellScript "entr-reload" ''
            ${self.packages.${system}.default}
            ${lib.getExe pkgs.nodePackages.live-server} \
              --watch=resume.html --open=resume.html --wait=300 &
            printf "\n%s" resume.{toml,nix,json} |
              ${lib.getExe pkgs.xe} -s 'test -f "$1" && echo "$1"' |
              ${lib.getExe pkgs.entr} -p ${self.packages.${system}.default}
          ''
        );
      };
```

Feel free to upstream it

**Comment by etu** [comment]
Thanks for the suggestion! I've updated the template and adapted some other improvements as well :slightly_smiling_face: 

I also renamed `nix-to-json` to `fmt-as-json`, the old name is still there to not be a breaking change. The `nix-to-json` name comes from only supporting nix as format :slightly_smiling_face:
