### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by mbrydak** [TaserudConsulting/jsonresume-nix#22]
Hey!

First off, thanks for setting up this Nix flake – super handy! I've been playing around with it and thought it might be useful to throw a license on the repo when you have a minute. Just helps everyone know what's cool and what's not with using and contributing to the project.

No biggie if you're swamped, just thought it might help boost the project's approachability for others looking to contribute or fork.

Cheers!

Max

**Comment by etu** [comment]
I was puzzled about this like "I can't believe that I've missed this" kind of puzzled. However now I'm yet again puzzled since I do see a license file in the root directory of the `main` branch.

So I guess it should be fine? :slightly_smiling_face:

**Comment by mbrydak** [comment]
Oh, now I'm double puzzled since I was dead sure that I've double checked the code before submitting the issue.

Sorry, my bad 😅
